name : First WorkFlow
on: [push]

jobs:
  run-shell-commands:
    runs-on:  windows-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command 
        run: |  
          D:\Program Files\nodejs\node -v
          D:\Program Files\nodejs\node_modules\npm\npm